MODULE PARAMETER_MODULE ! USEFUL CONSTANTS FOR ALL SUBROUTINES & ALL ELEMENTS

IMPLICIT NONE

! COMMON PARAMETERS ************************************************************

!DEFINE REAL NUMBER PRECISION TO BE EQUIVALENT TO F77 DOUBLE PRECISION
INTEGER, PARAMETER :: DP = SELECTED_REAL_KIND(14)

! I/O UNIT NO. FOR MESSAGE FILE
INTEGER, PARAMETER :: MSG_FILE = 6

! PARAMETERS FOR ERROR MESSAGE LENGTH AND ERROR STATUS VALUES
INTEGER, PARAMETER :: MSGLENGTH    = 256  ! LENGTH FOR ERROR MASSAGE
INTEGER, PARAMETER :: STAT_SUCCESS = 0    ! SUCCESSFUL STATUS VALUE
INTEGER, PARAMETER :: STAT_FAILURE = 1    ! FAILURE    STATUS VALUE

! VARIOUS CHARACTER LENGTH PARAMETERS
INTEGER, PARAMETER :: MATNAMELENGTH = 30  ! CHAR LEN OF A USER MATERIAL NAME
INTEGER, PARAMETER :: MATTYPELENGTH = 30  ! CHAR LEN OF A SYST MAT TYPE NAME
INTEGER, PARAMETER :: ELNAMELENGTH  = 30  ! CHAR LEN OF A USER ELEMENT NAME
INTEGER, PARAMETER :: ELTYPELENGTH  = 30  ! CHAR LEN OF A SYST ELEM TYPE NAME
INTEGER, PARAMETER :: SETNAMELENGTH = 30  ! CHAR LEN OF A SET NAME
INTEGER, PARAMETER :: DIRLENGTH     = 256 ! CHAR LEN OF A DIRECTORY NAME


! SOME COMMON REAL NUMBERS
REAL(KIND=DP), PARAMETER :: ZERO  = 0._DP,  ONE  = 1._DP,  TWO  = 2._DP,      &
                          & THREE = 3._DP,  FOUR = 4._DP,  FIVE = 5._DP,      & 
                          & SIX   = 6._DP,  SEVEN= 7._DP,  EIGHT= 8._DP,      &
                          & NINE  = 9._DP,  TEN  = 10._DP, NINETY= 90._DP

REAL(KIND=DP), PARAMETER :: HALF = 0.5_DP,  QUARTER = 0.25_DP

REAL(KIND=DP), PARAMETER :: ONE_THIRD  = ONE/THREE,  TWO_THIRD  = TWO/THREE,  &
                          & ONE_SIXTH  = ONE/SIX,    ONE_EIGHTH = ONE/EIGHT,  &
                          & ROOT3      = ONE/SQRT(THREE)

REAL(KIND=DP), PARAMETER :: HALFCIRC = 180._DP, PI =3.14159265359_DP

REAL(KIND=DP), PARAMETER :: TOLERANCE = 0.1_DP
!REAL(KIND=DP), PARAMETER :: SMALLNUM  = FIVE * TINY(ONE)
REAL(KIND=DP), PARAMETER :: SMALLNUM  = EPSILON(ONE)



! RESIDUAL MODULUS AFTER FAILURE 
! SET TO ONE MPA (OR OTHER UNIT) TO PREVENT NODES RUN WILD 
REAL(KIND=DP), PARAMETER :: RESIDUAL_MODULUS = ONE    

! GENERIC PARAMETER FOR INTACT STATE (ELEM, EDGE, MATERIAL, ETC.)
INTEGER, PARAMETER :: INTACT = 0 

! DERIVED DATA TYPE SDV_ARRAY, JUST TO GROUP 3 TYPES OF ARRAYS TOGETHER
TYPE :: SDV_ARRAY
    REAL(KIND=DP),  ALLOCATABLE :: R(:)
    INTEGER,        ALLOCATABLE :: I(:)
    LOGICAL,        ALLOCATABLE :: L(:)
END TYPE

TYPE :: INT_ALLOC_ARRAY
    INTEGER,    ALLOCATABLE :: ARRAY(:)
END TYPE

TYPE :: REAL_ALLOC_ARRAY
    REAL(DP),   ALLOCATABLE :: ARRAY(:)
END TYPE

! ******************************************************************************





! LAMINA MATERIAL MODULE PARAMETERS --------------------------------------------
INTEGER, PARAMETER :: MATRIX_ONSET = 5,  MATRIX_FAILED = 10,                  &
                    & FIBRE_ONSET  = 15, FIBRE_FAILED  = 20
!-------------------------------------------------------------------------------



! INTERFACE MATERIAL MODULE PARAMETERS -----------------------------------------
INTEGER, PARAMETER :: DELAM_ONSET = 5,  DELAM_FAILED = 10
!-------------------------------------------------------------------------------



! EDGE STATUS VARIABLE VALUES --------------------------------------------------
INTEGER, PARAMETER :: TRANSITION_EDGE = 1, REFINEMENT_EDGE   = 2,             &
                    & CRACK_TIP_EDGE  = 3, WEAK_CRACK_EDGE   = 3,             &
                    & COH_CRACK_EDGE  = 4, STRONG_CRACK_EDGE = 5
!-------------------------------------------------------------------------------



! XBRICK ELEMENT STATUS VARIABLE VALUES ----------------------------------------
INTEGER, PARAMETER :: TRANSITION_XBRICK   = 1, REFINEMENT_XBRICK  = 2,        &
                    & CRACK_TIP_XBRICK    = 3, CRACK_WAKE_XBRICK  = 4,        &
                    & MATRIX_CRACK_XBRICK = 5, FIBRE_FAIL_XBRICK  = 15
!-------------------------------------------------------------------------------



! XCOH AND SUBXCOH ELEM STATUS VARIABLES ---------------------------------------
INTEGER, PARAMETER :: FAIL1_XCOH    = 5, FAIL2_XCOH    = 6, FAIL3_XCOH    = 7
INTEGER, PARAMETER :: FAIL1_SUBXCOH = 5, FAIL2_SUBXCOH = 6, FAIL3_SUBXCOH = 7
!-------------------------------------------------------------------------------









CONTAINS






SUBROUTINE EXIT_FUNCTION
    STOP"**EXIT FUNCTION REACHED**"
    !WRITE(MSG_FILE,*) "**EXIT FUNCTION REACHED**"
    !CALL XIT    ! ABAQUS EXIT FUNCTION
END SUBROUTINE






END MODULE PARAMETER_MODULE
