MODULE PARAMETER_MODULE ! USEFUL CONSTANTS FOR ALL SUBROUTINES & ALL ELEMENTS

IMPLICIT NONE

INTEGER, PARAMETER :: DP=SELECTED_REAL_KIND(14) !-EQUIVALENT TO F77 DOUBLE PRECISION

INTEGER, PARAMETER :: MSG_FILE=6 ! I/O FILE INDEX FOR MESSAGE FILE

INTEGER, PARAMETER :: MSGLENGTH = 256  ! LENGTH FOR ERROR MASSAGE
INTEGER, PARAMETER :: STAT_SUCCESS = 0
INTEGER, PARAMETER :: STAT_FAILURE = 1

INTEGER, PARAMETER :: MATNAMELENGTH = 30  ! CHARACTER LENGTH OF A USER-INPUT MATERIAL NAME
INTEGER, PARAMETER :: MATTYPELENGTH = 30  ! CHARACTER LENGTH OF A SYSTEM MATERIAL TYPE NAME
INTEGER, PARAMETER :: ELNAMELENGTH  = 30  ! CHARACTER LENGTH OF A USER-INPUT ELEMENT NAME
INTEGER, PARAMETER :: ELTYPELENGTH  = 30  ! CHARACTER LENGTH OF A SYSTEM ELEMENT TYPE NAME
INTEGER, PARAMETER :: SETNAMELENGTH = 30  ! CHARACTER LENGTH OF A SET NAME
INTEGER, PARAMETER :: DIRLENGTH     = 256 ! CHARACTER LENGTH OF A DIRECTORY NAME

! SOME COMMON REAL NUMBERS
REAL(KIND=DP), PARAMETER :: ZERO=0._DP,ONE=1._DP,TWO=2._DP, &
& THREE=3._DP,FOUR=4._DP,FIVE=5._DP,SIX=6._DP,SEVEN=7._DP,      &
& EIGHT=8._DP,NINE=9._DP,TEN=10._DP,HALF=0.5_DP,QUARTER=0.25_DP,&
& ONE_THIRD=ONE/THREE,TWO_THIRD=TWO/THREE,ONE_SIXTH=ONE/SIX,    &
& ONE_EIGHTH=ONE/EIGHT,ROOT3=ONE/SQRT(THREE),                   &
& HALFCIRC=180._DP,PI=3.14159265359_DP,NINETY=90._DP            &
& ,TOLERANCE=0.1_DP

REAL(KIND=DP), PARAMETER :: SMALLNUM = FIVE * TINY(ONE)


! RESIDUAL STIFFNESS
REAL(KIND=DP), PARAMETER :: RESIDUAL_MODULUS=ONE    ! ONE MPA (OR OTHER UNIT) OF RESIDUAL STIFFNESS AFTER FAILURE, TO PREVENT NODES RUN WILD 

! GENERIC PARAMETER FOR INTACT STATE (ELEM, EDGE, MATERIAL, ETC.)
INTEGER, PARAMETER :: INTACT=0 

! INTERFACE MATERIAL MODULE PARAMETERS
INTEGER, PARAMETER :: COHMAT_ONSET=5, COHMAT_FAILED=10

! LAMINA MATERIAL MODULE PARAMETERS
INTEGER, PARAMETER :: MATRIX_ONSET=5, MATRIX_FAILED=10, FIBRE_ONSET=15, FIBRE_FAILED=20

! EDGE STATUS VARIABLE VALUES
INTEGER, PARAMETER :: EGTRANS=1, EGREF=2, EGTIP=3, WKCRACK=3, COHCRACK=4, STRGCRACK=5

! XBRICK ELEMENT STATUS VARIABLE VALUES
INTEGER, PARAMETER :: ELTRANS=1, ELREF=2, ELTIP=3, ELWAKE=4, ELFAILM=5, ELFAILF=15

! XCOH AND SUBXCOH ELEM STATUS VARIABLES 
INTEGER, PARAMETER :: ELFAIL1=5, ELFAIL2=6, ELFAIL3=7



! DERIVED DATA TYPE SDV_ARRAY, JUST TO GROUP 3 TYPES OF ARRAYS TOGETHER
TYPE :: SDV_ARRAY
    REAL(KIND=DP),  ALLOCATABLE :: R(:)
    INTEGER,        ALLOCATABLE :: I(:)
    LOGICAL,        ALLOCATABLE :: L(:)
END TYPE

TYPE :: SDV_LAMINA
    REAL(KIND=DP) :: DF = ZERO, U0  = ZERO, UF  = ZERO
    INTEGER,      :: FSTAT = INTACT, FFSTAT = INTACT, MFSTAT = INTACT
END TYPE

TYPE :: INT_ALLOC_ARRAY
    INTEGER,    ALLOCATABLE :: ARRAY(:)
END TYPE

TYPE :: REAL_ALLOC_ARRAY
    REAL(DP),   ALLOCATABLE :: ARRAY(:)
END TYPE

CONTAINS

SUBROUTINE EXIT_FUNCTION
    STOP"**EXIT FUNCTION REACHED**"
    !WRITE(MSG_FILE,*) "**EXIT FUNCTION REACHED**"
    !CALL XIT    ! ABAQUS EXIT FUNCTION
END SUBROUTINE

END MODULE PARAMETER_MODULE
